### ISSUE TITLE
Lisp error: error "Selecting deleted buffer"

### ISSUE THREAD

**Issue by arvids** [adamrt/sane-term#7]
So if I create several terms at once using sane-term-create, and then kill them of with ido-kill-buffer,
I get the following backtrace:

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  term-emulate-terminal(#<process *ansi-term*<3>> "^M\n^M\n^[[30m^[[m")
```

**Comment by adamrt** [comment]
Thanks for the report!

I'm unable to reproduce this bug. I've seen this bug from some other reports (org-mode, etc) and it usually is some other configuration, but I can't be certain.

Can you reproduce this bug? If so, would you mind sending me the exact steps to reproduce it and I'll be happy to dig in to it.

**Comment by arvids** [comment]
Sorry for the late reply, I am traveling at the moment.
This is my configuration for ansi-term/sane-term:

```
;; unicode in ansi-term
(defadvice ansi-term (after advise-ansi-term-coding-system)
    (set-buffer-process-coding-system 'utf-8-unix 'utf-8-unix))
(ad-activate 'ansi-term)

;; Use Emacs terminfo, not system terminfo
(setq system-uses-terminfo nil)

(require 'sane-term)
(global-set-key (kbd "C-x T") 'sane-term-create)
(global-set-key (kbd "C-x t") 'sane-term)

(global-set-key (kbd "S-s-SPC") 'sane-term-create)
(global-set-key (kbd "s-SPC") 'sane-term)

;; Set $SHELL (fish) as shell
(when (getenv "SHELL")
  (setq sane-term-shell-command (getenv "SHELL")))
```

I am able to reproduce it with my configuration, I can troubleshoot more in a week.

**Comment by adamrt** [comment]
Thanks for replying. I found a similar report that explains some of what is happening here https://github.com/syl20bnr/spacemacs/issues/605

Can you see if you can replicate it by running `emacs -Q` to ignore your configuration and then just use the configuration you have above? I'm unable to replicate it some I'm thinking it may be some hook you have running or something similar.

Also, side note: I just updated `sane-term` to use `(getenv "SHELL")` for the default `sane-term-shell-command` so you can remove that configuration as well.

**Comment by arvids** [comment]
Yup, error still seems to come up with just ansi-term in emacs -Q,
```
error in process filter: Selecting deleted buffer [2 times]
```
So it seem you are in the clear:) 
Thank you for your help.

**Comment by adamrt** [comment]
Thank you
